
import { Mentor } from '@/types/mentor';

export const mockMentors: Mentor[] = [
  {
    id: '1',
    name: 'Jane Doe',
    title: 'Frontend Developer @ DCODE',
    avatarUrl: '/hatch.png',
    status: 'Available',
    expertise: ['JavaScript', 'React', 'Next.js', 'Tailwind CSS'],
    rating: 4.9,
    sessionsCompleted: 120,
  },
  {
    id: '2',
    name: 'John Smith',
    title: 'Backend Engineer @ Google',
    avatarUrl: '/hatch.png',
    status: 'Busy',
    expertise: ['Python', 'Django', 'PostgreSQL', 'Docker'],
    rating: 4.8,
    sessionsCompleted: 250,
  },
  {
    id: '3',
    name: 'Emily White',
    title: 'Full-Stack Developer',
    avatarUrl: '/hatch.png',
    status: 'Offline',
    expertise: ['TypeScript', 'Node.js', 'GraphQL', 'AWS'],
    rating: 4.9,
    sessionsCompleted: 80,
  },
  {
    id: '4',
    name: 'Michael Brown',
    title: 'DevOps Specialist @ Microsoft',
    avatarUrl: '/hatch.png',
    status: 'Available',
    expertise: ['Kubernetes', 'Terraform', 'CI/CD', 'Azure'],
    rating: 4.7,
    sessionsCompleted: 150,
  },
  {
    id: '5',
    name: 'Sarah Green',
    title: 'UI/UX Designer & Developer',
    avatarUrl: '/hatch.png',
    status: 'Available',
    expertise: ['Figma', 'React', 'CSS', 'User Research'],
    rating: 5.0,
    sessionsCompleted: 200,
  },
    {
    id: '6',
    name: 'David Lee',
    title: 'Data Scientist @ Meta',
    avatarUrl: '/hatch.png',
    status: 'Busy',
    expertise: ['Python', 'PyTorch', 'Pandas', 'Machine Learning'],
    rating: 4.9,
    sessionsCompleted: 180,
  },
  {
    id: '7',
    name: 'Chris Taylor',
    title: 'Mobile Developer @ Apple',
    avatarUrl: '/hatch.png',
    status: 'Offline',
    expertise: ['Swift', 'iOS', 'Kotlin', 'Android'],
    rating: 4.8,
    sessionsCompleted: 95,
  },
  {
    id: '8',
    name: 'Alex Johnson',
    title: 'Security Engineer',
    avatarUrl: '/hatch.png',
    status: 'Available',
    expertise: ['Cybersecurity', 'Penetration Testing', 'Cryptography'],
    rating: 4.9,
    sessionsCompleted: 110,
  },
];
